services:
  quartet_webpay.checkout.payment.form_factory:
    class: Quartet\WebPayBundle\Form\Factory\PaymentFormFactory
    arguments:
      - @form.factory

  quartet_webpay.checkout.payment.handler.update_customer:
    class: Quartet\WebPayBundle\Handler\PaymentHandler\UpdateCustomerHandler
    arguments:
      - @quartet_webpay
      - @security.context
      - @quartet_webpay.customer_manager

  quartet_webpay.checkout.payment_manager.session:
    public: false
    class: Quartet\WebPayBundle\Session\PaymentManager
    arguments:
      - @session

  quartet_webpay.checkout.handler.chain:
    abstract: true
    class: Quartet\WebPayBundle\Handler\PaymentHandler\ChainHandler

  quartet_webpay.checkout.payment.handler.default:
    public: false
    parent: quartet_webpay.checkout.handler.chain
    arguments:
      - @quartet_webpay.checkout.payment.handler.update_customer
      - @quartet_webpay.checkout.payment.handler.store_payment

  quartet_webpay.checkout.payment.handler.update_customer:
    public: false
    class: Quartet\WebPayBundle\Handler\PaymentHandler\UpdateCustomerHandler
    arguments:
      - @quartet_webpay
      - @quartet_webpay.customer_manager
      - %quartet_webpay.checkout.payment.persistence%

  quartet_webpay.checkout.payment.handler.store_payment:
    public: false
    class: Quartet\WebPayBundle\Handler\PaymentHandler\StorePaymentHandler
    arguments:
      - @quartet_webpay.checkout.payment_manager
