services:
  quartet_webpay.form_type.token:
    class: Quartet\WebPayBundle\Form\Type\TokenFormType
    arguments:
      - %quartet_webpay.api_public%
    tags:
      - { name: form.type, alias: quartet_webpay_token }

  quartet_webpay.form_type.payment:
    class: Quartet\WebPayBundle\Form\Type\PaymentFormType
    arguments:
      - %quartet_webpay.checkout.payment_class%
    tags:
      - { name: form.type, alias: quartet_webpay_payment }
