services:
  quartet_webpay_client:
    class: WebPay\WebPay
    arguments:
      - %quartet_webpay.api_secret%
      - %quartet_webpay.api_base%

  quartet_webpay.customers:
    class: WebPay\Api\Customers
    factory_service: quartet_webpay_client
    factory_method: __get
    arguments:
      - customers

  quartet_webpay.account:
    class: WebPay\Api\Account
    factory_service: quartet_webpay_client
    factory_method: __get
    arguments:
      - account

  quartet_webpay.tokens:
    class: WebPay\Api\Tokens
    factory_service: quartet_webpay_client
    factory_method: __get
    arguments:
      - tokens

  quartet_webpay.events:
    class: WebPay\Api\Events
    factory_service: quartet_webpay_client
    factory_method: __get
    arguments:
      - events

  quartet_webpay.charges:
    class: WebPay\Api\Charges
    factory_service: quartet_webpay_client
    factory_method: __get
    arguments:
      - charges
