services:
  quartet_webpay_client:
    class: WebPay\WebPay
    arguments:
      - %quartet_webpay.api_secret%
      - %quartet_webpay.api_base%

  quartet_webpay.customers:
    class: WebPay\Api\Customers
    factory_service: quartet_webpay_client
    factory_method: __get
    arguments:
      - customers
