services:
  quartet_webpay_client:
    class: WebPay\WebPay
    arguments:
      - "%quartet_webpay.api_secret%"
      - "%quartet_webpay.api_base%"

  quartet_webpay.accessor:
    abstract: true
    factory: ["@quartet_webpay_client", __get]

  quartet_webpay.customers:
    parent: quartet_webpay.accessor
    class: WebPay\Api\Customers
    arguments:
      - customers

  quartet_webpay.account:
    parent: quartet_webpay.accessor
    class: WebPay\Api\Account
    arguments:
      - account

  quartet_webpay.tokens:
    parent: quartet_webpay.accessor
    class: WebPay\Api\Tokens
    arguments:
      - tokens

  quartet_webpay.events:
    parent: quartet_webpay.accessor
    class: WebPay\Api\Events
    arguments:
      - events

  quartet_webpay.charges:
    parent: quartet_webpay.accessor
    class: WebPay\Api\Charges
    arguments:
      - charges

  quartet_webpay.twig_extension:
    class: Quartet\Bundle\WebPayBundle\Twig\Extension\WebPayExtension
    arguments:
      - "%quartet_webpay.test%"
    tags:
      - { name: twig.extension }
